---
title: "Week 7 Exercises"
output: html_notebook
---

```{r setup}
library(tidyverse)
```

# Alternative Assignment 

#### 1.1 Import data and data wrangling

```{r}
# import fss_learning data
fss <- read.csv(file.choose())
fss
```

```{r}
# look at the data
fss
str(fss)
summary(fss)
glimpse(fss)
# transform "participant" to factor variable
fss <- fss %>% 
  mutate(participant = factor(participant))
```


```{r}
# log-transformed cumrun(x-axis) and duration(y-axis)
fss_wise <- fss %>%
  mutate(cumrun_log = log(cumrun+1), 
  duration_log = log(duration+1))
fss_wise
```
```{r}
# participant-wise，standardize by participants
fss_wise_1 <- fss_wise %>%
  mutate(Z_flow = flow - mean(flow, na.rm = TRUE)/ sd(flow, na.rm = TRUE)) 
fss_wise_1
```


```{r fig.width=12, fig.height=10}
# plot the results
library(ggplot2)
ggplot(data = fss_wise_1, aes(x = cumrun_log, y = duration_log, color = Z_flow))+
  geom_point()+
  geom_smooth(method = "lm", alpha = .2, color = "red")+
  labs(x = "In(Cumulative runs)", y = "In(duration)", title = "Performance in CogCarSim")+
  facet_wrap(~participant) +
  scale_color_gradient(low = "green", high = "black")+
  theme_bw() +
  theme(legend.position = "bottom")
```

